
services:

  django:
    container_name: django
    build: srcs/django
    env_file:
      - .env
    ports:
      - "${PORT}:80"
    volumes:
      - transcendence:/django/mysite/
    networks:
      - my_network

  postgresql:
    container_name: postgresql
    build: srcs/postgreSQL
    env_file:
      - .env
#    volumes:
#      - database:/usr/local/pgsql/data
    networks:
      - my_network

volumes:

  transcendence:
    driver: local
    driver_opts:
      type: none
      device: ${DJANGO_VOLUME_PATH}
      o: bind
  
#  database:
#    driver: local
#    driver_opts:
#      type: none
#      device: ${POSTGRESQL_VOLUME_PATH}
#      o: bind

networks:
  my_network:
    driver: bridge