FROM debian:bullseye

ARG DB_NAME=${DB_NAME}
ARG DB_USER=${DB_USER}
ARG DB_PASS=${DB_PASS}

RUN apt -y update && apt install -y \
	sudo \
	postgresql

RUN mkdir -p /usr/local/pgsql/data && \
	chown postgres /usr/local/pgsql/data && \
	sudo -u postgres /usr/lib/postgresql/*/bin/initdb -D /usr/local/pgsql/data && \
	sudo -u postgres /usr/lib/postgresql/*/bin/pg_ctl -D /usr/local/pgsql/data start && \
	sudo -u postgres /usr/lib/postgresql/*/bin/createdb ${DB_NAME} && \
	sudo -u postgres /usr/lib/postgresql/*/bin/psql -c "CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASS}';" && \
	sudo -u postgres /usr/lib/postgresql/*/bin/pg_ctl -D /usr/local/pgsql/data stop && \
	sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/g" /usr/local/pgsql/data/postgresql.conf && \
	echo "host    all             all             0.0.0.0/0                 md5" | tee -a /usr/local/pgsql/data/pg_hba.conf
	
CMD [ "sudo", "-u", "postgres", "/usr/lib/postgresql/13/bin/postgres", "-D", "/usr/local/pgsql/data" ]