FROM debian:bullseye

WORKDIR /django

RUN apt -y update && apt install -y \
	python3 \
	python3-venv

COPY requirements.txt .
RUN python3 -m venv env && \
	. env/bin/activate && \
	pip install -r requirements.txt


COPY data/mysite ./mysite
COPY tools/django_setup.sh .
RUN chmod +x django_setup.sh

CMD ["./django_setup.sh"]
