FROM debian:bullseye

WORKDIR /django

COPY requirements.txt .

RUN apt update && apt upgrade && \
	apt install -y python3 python3-venv
RUN python3 -m venv env
RUN . env/bin/activate && pip install -r requirements.txt
RUN . env/bin/activate && django-admin startproject transcendance

EXPOSE 8000

CMD ["env/bin/python", "transcendance/manage.py", "runserver", "0.0.0.0:80"] 
